# Broadcasting : Basics

## Example : 1

In this matrix, are shown the number of calories from carbohydrates, proteins, and fats in 100 grams of four different foods: apples, beef, eggs, and potatoes.

$$ A=   \begin{bmatrix}
        56.0 & 0.0 & 4.4 & 68.0\\
        1.2 & 104.0 & 52.0 & 8.0\\
        1.8 & 135.0 & 99.0 & 0.9
        \end{bmatrix}$$

Now, let's say your goal is to calculate the percentage of calories from carbs, proteins and fats for each of the four foods.  

To do this, with one line of Python code we're going to sum down the columns. Then,a second line of Python code to divide each of the four columns by their corresponding sum, to find out the percentage composition.

In [3]:
import numpy as np

A = np.array([[56.0,0.0,4.4,68.0],
              [1.2,104.0,52.0,8.0],
              [1.8,135.0,99.0,0.9]])

print(A)

[[ 56.    0.    4.4  68. ]
 [  1.2 104.   52.    8. ]
 [  1.8 135.   99.    0.9]]


In [4]:
cal = A.sum(axis=0)  #to sum vertically
print(cal)

[ 59.  239.  155.4  76.9]


In [5]:
percentage = 100*A/cal.reshape(1,4)
print(percentage)

[[94.91525424  0.          2.83140283 88.42652796]
 [ 2.03389831 43.51464435 33.46203346 10.40312094]
 [ 3.05084746 56.48535565 63.70656371  1.17035111]]


Here, in line(4): (axis = 0), means that you want Python to sum vertically. Further, line(5) is an example of Python broadcasting, where you take a matrix A, a three by four matrix and divide it by a one by four matrix, cal. 

So with this, we have found the percentage composition of carbs, proteins and fats in apples, beef, eggs and potatoes by broadcasting.